### ISSUE TITLE
There is no description 

### ISSUE THREAD

**Issue by Elshirak** [Sonovrik/Base_Functions_Assembler#1]
Hi, Denis! 
Interesting work, however there is no description about the project, so could you add it to make watchers better understand what have you done? Is it 42 Ecole project? 
Thank you in advance

**Comment by Sonovrik** [comment]
Yes it's ecole 42 project
If u don't know anything about C/C++ language just go out the window 
FK u

**Comment by Elshirak** [comment]
Nice, thanks
